### ISSUE TITLE
Vite server can't launch

### ISSUE THREAD

**Issue by JVT038** [dcodegroup/vite-plugin-laravel-translations#14]
When I launch Vite with this plugin, I see this error in the CLI and the server instantly stops.

```
error when starting dev server:
TypeError: Cannot read properties of undefined (reading 'sync')
    at buildTranslations (C:\folder\to\project\node_modules\vite-plugin-laravel-translations\dist\loader.js:55:34)
    at config (C:\folder\to\project\node_modules\vite-plugin-laravel-translations\dist\vite.js:33:65)
    at runConfigHook (file:///C:/\folder\to\project/node_modules/vite/dist/node/chunks/dep-79892de8.js:64005:31)
    at async resolveConfig (file:///C:/\folder\to\project/node_modules/vite/dist/node/chunks/dep-79892de8.js:63499:14)
    at async createServer (file:///C:/\folder\to\project/node_modules/vite/dist/node/chunks/dep-79892de8.js:62752:20)
    at async CAC.<anonymous> (file:///C:/\folder\to\project/node_modules/vite/dist/node/cli.js:734:24
```
This is my `vite.config.js`:
```javascript
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import laravelTranslations from 'vite-plugin-laravel-translations';

require('dotenv');
const path = require('path');

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/sass/app.scss',
                'resources/js/app.js',
            ],
            refresh: true,
        }),
        laravelTranslations({
            namespace: 'translation'
        })
    ],
    resolve: {
        alias: {
            '~/bootstrap-icons': path.resolve(__dirname, 'node_modules/bootstrap-icons/'),
        }
    },
    server: {
        hmr: {
            host: 'localhost',
        },
        port: process.env.VITE_SERVER_PORT
    }
});
```

**Comment by immersedone** [comment]
@JVT038 can you try install this particular branch to see if the problem still exists?

https://github.com/dcodegroup/vite-plugin-laravel-translations/tree/hotfix/patch-issue-with-windows-environments

**PNPM:** 
`pnpm i -D "https://github.com/dcodegroup/vite-plugin-laravel-translations/tarball/hotfix/patch-issue-with-windows-environments"`

**NPM:** 
`npm i -D "https://github.com/dcodegroup/vite-plugin-laravel-translations/tarball/hotfix/patch-issue-with-windows-environments"`
